/**
 * Records the walkthrough video.
 *
 *   npx tsx scripts/record-demo.mts [--base-url URL] [--out docs/verity-demo.mp4]
 *
 * Drives the real site with Playwright, captures full-page screenshots at each
 * beat, then hands the frames to caption-frames.py and ffmpeg. Nothing is
 * staged: the numbers in the video are whatever the deployment returns while
 * this runs, and a failed step fails the recording rather than being edited out.
 */
import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

import { chromium, type Page } from "@playwright/test";

const FRAME_DIR = ".demo-frames";

function stringArg(name: string, fallback: string): string {
  const i = process.argv.indexOf(`--${name}`);
  return i === -1 ? fallback : process.argv[i + 1];
}

interface Beat {
  /** Caption rendered above the screenshot. */
  caption: string;
  /** Seconds this beat stays on screen. */
  hold: number;
}

const beats: Beat[] = [];

/**
 * Scrolls the element a beat is about into view.
 *
 * Fixed pixel offsets were used here first, and they drift: expanding the trace
 * table pushes everything below it down, so a caption about citation grounding
 * ended up over a screenshot of the trace. Framing a beat by the thing it
 * describes cannot go out of sync with itself.
 */
async function frame(page: Page, heading: RegExp | string, offset = 90) {
  const target = page.getByRole("heading", { name: heading }).first();
  await target.scrollIntoViewIfNeeded();
  await page.evaluate((o) => window.scrollBy({ top: -o }), offset);
  await page.waitForTimeout(500);
}

async function shot(page: Page, index: number, caption: string, hold: number, fullPage = false) {
  await page.screenshot({
    path: path.join(FRAME_DIR, `${String(index).padStart(3, "0")}.png`),
    fullPage,
  });
  beats.push({ caption, hold });
}

async function main() {
  const baseUrl = stringArg("base-url", "https://verity-compliance.vercel.app");
  const out = stringArg("out", "docs/verity-demo.mp4");

  await rm(FRAME_DIR, { recursive: true, force: true });
  await mkdir(FRAME_DIR, { recursive: true });

  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });

  let i = 0;
  console.log(`Recording against ${baseUrl}`);

  // 1. The overview, with the index numbers it reads at render time.
  await page.goto(baseUrl, { waitUntil: "networkidle" });
  await shot(page, i++, "Verity reads a document, finds the regulations that apply, and cites them.", 4.5);

  await frame(page, /what is in the index/i);
  await shot(page, i++, "413 sections of real regulation text. 1,147 retrievable passages, embedded at 768 dimensions.", 4.5);

  // 2. The retrieval playground: three arms, one query.
  await page.goto(`${baseUrl}/search`, { waitUntil: "networkidle" });
  await page.getByLabel("Search query").fill(
    "A laptop with 900 patient files was stolen from a car. What do we now owe, and to whom?"
  );
  await shot(page, i++, "The retrieval playground runs one query through every configuration at once.", 4);

  await page.getByRole("button", { name: "Search" }).click();
  await page.getByRole("heading", { name: "Dense", exact: true }).waitFor({ timeout: 60_000 });
  await page.waitForTimeout(800);
  await frame(page, "Dense", 140);
  await shot(page, i++, "Dense retrieval finds the breach-notification sections. BM25, on this phrasing, does not.", 5.5);

  // 3. The reranker, which is the measured win.
  await page.getByLabel(/add the llm reranker/i).check();
  await page.getByRole("button", { name: "Search" }).click();
  await page.getByRole("status").waitFor({ timeout: 10_000 }).catch(() => {});
  await shot(page, i++, "Turning on the reranker. Previous results stay on screen — it takes about ten seconds.", 3.5);

  const rerankArm = page.getByRole("heading", { name: "Hybrid + rerank", exact: true });
  await rerankArm.waitFor({ timeout: 90_000 });
  await page.waitForTimeout(800);
  // Scrolled to the rerank column specifically. It wraps onto a second row at
  // this viewport, so a fixed scroll offset shows three arms while the caption
  // talks about the fourth.
  await rerankArm.scrollIntoViewIfNeeded();
  await page.evaluate(() => window.scrollBy({ top: -120 }));
  await page.waitForTimeout(500);
  await shot(page, i++, "The reranker reorders the fused candidates. On the held-out set that is worth +0.11 nDCG.", 5.5);

  // 4. The evaluation, including the configuration that lost.
  await page.goto(`${baseUrl}/evaluation`, { waitUntil: "networkidle" });
  await page.waitForTimeout(600);
  await shot(page, i++, "Every number is generated by the harness against a committed gold set.", 4.5);

  await frame(page, /held-out slice/i);
  await shot(page, i++, "108 labelled queries, split dev and held-out. The one fitted parameter is chosen on dev alone.", 5.5);

  await frame(page, /choosing the fusion weight/i);
  await shot(page, i++, "The headline result is negative and the report leads with it: equal-weight fusion loses.", 5.5);

  // 5. The assessment, end to end, with the document visible.
  await page.goto(`${baseUrl}/assess`, { waitUntil: "networkidle" });
  await page.getByRole("button", { name: /load the sample document/i }).click();
  await page.waitForTimeout(500);
  await shot(page, i++, "The sample loads into the box, so every finding can be checked against the input.", 5);

  await page.getByRole("button", { name: /assess this document/i }).click();
  await page.waitForTimeout(1500);
  await shot(page, i++, "Classify, decompose into probes, retrieve, assess, then verify every quote.", 4);

  await page.getByRole("heading", { name: /what it read/i }).waitFor({ timeout: 180_000 });
  await page.waitForTimeout(1000);
  await shot(page, i++, "Roughly thirty seconds, with the tokens and the cost at published rates on screen.", 5);

  await page.getByRole("button", { name: /show the per-stage trace/i }).click();
  await page.waitForTimeout(700);
  await frame(page, /what it read/i);
  await shot(page, i++, "The per-stage trace: what ran, how long it took, how many tokens it spent.", 5.5);

  await frame(page, /citation grounding/i);
  await shot(page, i++, "Citation grounding: how many findings quoted text that was actually found in the source.", 5);

  // The first framework heading is the top of the findings, whatever the
  // classifier decided applied this run.
  const firstFramework = page.locator("section h2").filter({ hasText: /^[A-Z]/ }).last();
  await firstFramework.scrollIntoViewIfNeeded();
  await page.evaluate(() => window.scrollBy({ top: -90 }));
  await page.waitForTimeout(500);
  await shot(page, i++, "Each finding carries both quotes and the verdict on each — exact, near, or unsupported.", 6);

  await page.evaluate(() => window.scrollBy({ top: 620 }));
  await page.waitForTimeout(500);
  await shot(page, i++, "An unsupported finding would be shown as unsupported and excluded from the score.", 5.5);

  await browser.close();

  await writeFile(path.join(FRAME_DIR, "beats.json"), JSON.stringify(beats, null, 2), "utf8");
  console.log(`\n${beats.length} frames captured in ${FRAME_DIR}/`);
  console.log(`Next: python3 scripts/caption-frames.py ${FRAME_DIR} ${out}`);
}

main().catch((err) => {
  console.error("\nrecording failed:", err.message);
  process.exit(1);
});
